### ISSUE TITLE
Some thoughts from a visitor.

### ISSUE THREAD

**Issue by annieFromTaiwan** [aspspspsp/HoungYangInterview#1]
Thanks for your sharing in PTT
---
Hi, I am a visitor from PTT Soft_Job.
I'm interested in these Java interview problems so I tried writing some of them.
After seeing your code I thought maybe there are something I could share with you.
That's why I post this comment.

Prob `WordCount`
---

For that given test string, the right answer should be `the(13)`. 
However, your program outputs `the(11)`. 

I have this shorter test case. `It is the cat.The cat is cute.` This might help you better to find out your program's bug. For this test case, your program outputs `the(1)`, `catthe(1)`.

Prob `SortNames`
---

It seems the Comparator is unnecessary...

I think your code runs the same well even after deleting all the Comparator stuff.
Like this:

	static ArrayList<String> execute(String[] names) {
		ArrayList<String> result = new ArrayList<String>();
		
		// WRITE YOU CODE HERE -START-
		List<String> l_names = new ArrayList<String>();
		for(int i = 0; i < names.length; i ++) {
			l_names.add(names[i]);
		}
		Collections.sort(l_names);
		result = (ArrayList<String>)l_names;
		
		// WRITE YOU CODE HERE -END-
		return result;
	}

**Comment by annieFromTaiwan** [comment]
My code for prob `WordCount`

	static ArrayList<String> execute(String paragraph) {
		ArrayList<String> result = new ArrayList<String>();
		
		// WRITE YOU CODE HERE -START-
		paragraph = paragraph.toLowerCase();
		HashMap<String, Integer> counter = new HashMap<String, Integer>();
		
		Pattern p = Pattern.compile("[a-z]+");
		Matcher m = p.matcher(paragraph);
		while(m.find()) {
			String s = m.group();
			Integer v = counter.get(s);
			if(v != null) {
				counter.put(s, v+1);
			} else {
				counter.put(s, 1);
			}
		}
		
		// Find `max`, `secondMax`.
		Integer max = -1, secondMax = -1;
		for(Integer v:counter.values()) {
			if(v > max) {
				secondMax = max;
				max = v;
			}
			else if(v == max) {
				continue;
			}
			else if(v > secondMax) {
				secondMax = v;
			}
		}
		
		// Write to `result`.
		for(String k:counter.keySet()) {
			if(counter.get(k) == max) {
				result.add(0, k + "(" + max + ")");
			}
			if(counter.get(k) == secondMax) {
				result.add(k + "(" + secondMax + ")");
			}	
		}
		
		// WRITE YOU CODE HERE -END-
		
		return result;
	}

If there's anything that could be improved, please don't hesitate to tell me! We could review each other's code :) Thank you!

**Comment by annieFromTaiwan** [comment]
My code for problem `SortNames`

	static ArrayList<String> execute(String[] names) {
		ArrayList<String> result = new ArrayList<String>();
		
		// WRITE YOU CODE HERE -START-
		Arrays.sort(names);
		for(String name: names) {
			result.add(name);
		}
		// WRITE YOU CODE HERE -END-
		
		return result;
	}

Or another version, if this is allowed:

	static ArrayList<String> execute(String[] names) {
		Arrays.sort(names);
		return new ArrayList<String>(Arrays.asList(names));
	}

**Comment by aspspspsp** [comment]
I fixed the bug of word count, please check it out~
